name: Create sample files

on:
    push:
        branches: ['**']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # - name: Checkout repository
            #   uses: actions/checkout@v4
            #   with:
            #       lfs: true

            # - name: Setup Node.js
            #   uses: actions/setup-node@v4
            #   with:
            #       node-version: '18'
            #       cache: 'npm'

            # We "flatten" out each clients.zip-servers.zip pairing so that the
            # downloadable artifacts are nicely organized, one per platform.
            - name: Prepare and upload artifacts
              run: |
                  mkdir artifacts
                  platforms=("linux-arm64" "linux-x64" "mac-arm64" "mac-x64" "win-x64")
                  for platform in "${platforms[@]}"; do
                    mkdir -p "artifacts/$platform"
                    echo "$platform" > artifacts/$platform/$platform.txt
                  done
                  ls -al artifacts

            - name: Upload linux-arm64
              uses: actions/upload-artifact@v4
              with:
                  name: linux-arm64
                  path: artifacts/linux-arm64/
                  if-no-files-found: error

            - name: Upload linux-x64
              uses: actions/upload-artifact@v4
              with:
                  name: linux-x64
                  path: artifacts/linux-x64/
                  if-no-files-found: error

            - name: Upload mac-arm64
              uses: actions/upload-artifact@v4
              with:
                  name: mac-arm64
                  path: artifacts/mac-arm64/
                  if-no-files-found: error

            - name: Upload mac-x64
              uses: actions/upload-artifact@v4
              with:
                  name: mac-x64
                  path: artifacts/mac-x64/
                  if-no-files-found: error

            - name: Upload win-x64
              uses: actions/upload-artifact@v4
              with:
                  name: win-x64
                  path: artifacts/win-x64/
                  if-no-files-found: error
